<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<div data-role="footer" class="page-footer product-view-page-footer" style="background-color: gray">
    <div class="ui-grid-a">
        <div class="ui-block-a">
            <button title="<?php echo $buttonTitle ?>" class="ui-btn ui-corner-all ui-btn-inline important-button" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        </div>
        <div class="ui-block-b">
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href);
                        return false;" class="ui-btn ui-corner-all ui-btn-inline interesting-button"><?php echo $this->__('Add to Wishlist') ?></a>
            <?php endif; ?>
        </div>

    </div>
</div><!-- /footer -->