<div class="header-nav-bar" style="display:none" id="header-nav-bar">
    <div class="navbar-tbl-type">
        <a href="<?php echo Mage::getBaseUrl() . $this->getLink()?>" class="navbar-tbl-cell">
            <span class="icon"><?php echo $this->__("Home") ?></span>
            <p style="color:#6e6e6e;"><?php echo $this->__("Home") ?></p>
        </a>
        <a href="" class="navbar-tbl-cell">
            <span class="icon2"><?php echo $this->__("Category") ?></span>
            <p style="color:#6e6e6e;"><?php echo $this->__("Category") ?></p>
        </a>
        <a href="<?php echo $this->getUrl('checkout/cart/index')?>" class="navbar-tbl-cell">
            <span class="icon3"><?php echo $this->__("Cart") ?></span>
            <p style="color:#6e6e6e;"><?php echo $this->__("Cart") ?></p>
        </a>
        <a href="<?php echo $this->getUrl('customer/account/index')?>" class="navbar-tbl-cell">
            <span class="icon4"><?php echo $this->__("Account") ?></span>
            <p style="color:#6e6e6e;"><?php echo $this->__("Account") ?></p>
        </a>
    </div>
</div>